"""CLI command: ``arandu chunk`` — build ChunkSets across one or more chunker views."""

from __future__ import annotations

import logging
from pathlib import Path  # noqa: TC003
from typing import Annotated

import typer

from arandu.shared.chunking.batch import run_chunk_batch
from arandu.shared.chunking.registry import KNOWN_CHUNKER_IDS
from arandu.utils.logger import print_error, print_info, print_success, print_warning

logger = logging.getLogger(__name__)


def chunk(
    input_dir: Annotated[
        Path,
        typer.Argument(
            help="Directory of EnrichedRecord JSON files (transcriptions).",
            exists=True,
            file_okay=False,
            dir_okay=True,
            readable=True,
        ),
    ],
    pipeline_id: Annotated[
        str | None,
        typer.Option(
            "--id",
            help=(
                "Pipeline ID for the run. Auto-generated by ResultsManager when "
                "omitted (e.g. ``YYYYMMDD_HHMMSS_local``). Reuse an existing ID to "
                "attach the chunk stage to that run."
            ),
        ),
    ] = None,
    views: Annotated[
        list[str] | None,
        typer.Option(
            "--view",
            help=(
                "Chunker view ID; repeatable. Known: "
                + ", ".join(KNOWN_CHUNKER_IDS)
                + ". Defaults to cep_4k."
            ),
        ),
    ] = None,
    rebuild: Annotated[
        bool,
        typer.Option(
            "--rebuild",
            help=(
                "Clear existing chunk outputs for the selected views and reset "
                "the checkpoint before chunking, for a clean re-run (e.g. to drop "
                "chunks of transcriptions the judge rejected)."
            ),
        ),
    ] = False,
) -> None:
    """Build ChunkSets across one or more chunker views.

    Reads every ``*.json`` file in ``input_dir`` as an ``EnrichedRecord``,
    slices ``transcription_text`` with each requested chunker view, and writes
    one ``ChunkSet`` per (view, source) pair to
    ``results/<pipeline_id>/chunk/outputs/<chunker_id>/<file_id>.json``.

    Stage scaffolding (``chunk_checkpoint.json``, ``run_metadata.json``, and
    the run-root ``pipeline.json``) is managed by ``ResultsManager``. See
    ``docs/development/architecture.md#results-directory-layout``.
    """
    selected_views: list[str] = views or ["cep_4k"]

    try:
        result = run_chunk_batch(
            input_dir=input_dir,
            views=selected_views,
            pipeline_id=pipeline_id,
            rebuild=rebuild,
        )
    except ValueError as exc:
        print_error(str(exc))
        raise typer.Exit(code=1) from exc

    if (
        result.sources_processed == 0
        and result.sources_resumed == 0
        and result.skipped == 0
        and result.skipped_invalid == 0
    ):
        print_warning(f"No JSON files found in {input_dir}")
        return

    if result.skipped:
        print_warning(f"Skipped {result.skipped} unreadable / non-EnrichedRecord file(s).")
    if result.skipped_invalid:
        print_warning(
            f"Skipped {result.skipped_invalid} transcription(s) rejected by the judge "
            "(is_valid=False)."
        )
    if result.sources_resumed:
        print_info(f"Resumed: {result.sources_resumed} source(s) already completed in checkpoint.")
    print_info(f"Run ID: {result.pipeline_id}")
    print_success(
        f"Wrote {result.chunk_sets_written} ChunkSet(s) "
        f"({result.sources_processed} source(s), {len(selected_views)} view(s)) "
        f"to {result.run_dir}/outputs/"
    )
