"""Chunking-stage batch orchestrator (`arandu chunk`).

Owns the `ResultsManager` plumbing for the chunking stage: writes
``ChunkSet`` artifacts to ``results/<pipeline_id>/chunk/outputs/<chunker_id>/<file_id>.json``
and emits the per-stage ``chunk_checkpoint.json`` + ``run_metadata.json``
siblings. One ``ChunkSet`` file per (chunker view, source file) pair, so
downstream retrievers can consume a single view directly without
extracting from a multi-view container. See
``docs/development/architecture.md#results-directory-layout`` for the
convention this orchestrator enforces.
"""

from __future__ import annotations

import hashlib
import logging
from datetime import UTC, datetime
from typing import TYPE_CHECKING

from pydantic import BaseModel, Field, ValidationError

from arandu.shared.checkpoint import CheckpointManager
from arandu.shared.chunking.registry import KNOWN_CHUNKER_IDS, get_chunker
from arandu.shared.chunking.schemas import Chunk, ChunkSet
from arandu.shared.config import ResultsConfig
from arandu.shared.results_manager import ResultsManager
from arandu.shared.schemas import EnrichedRecord, PipelineType

if TYPE_CHECKING:
    from pathlib import Path

logger = logging.getLogger(__name__)


CHECKPOINT_FILENAME = "chunk_checkpoint.json"


class ChunkBatchConfig(BaseModel):
    """Configuration snapshot persisted in the stage's ``run_metadata.json``."""

    input_dir: str = Field(..., description="Source directory of EnrichedRecord JSON files.")
    views: list[str] = Field(..., description="Chunker view IDs to emit.")


class ChunkBatchResult(BaseModel):
    """In-process return value summarising what the orchestrator processed.

    ``sources_processed`` is the unit-of-work count (one EnrichedRecord =
    one source) used for checkpoint and progress tracking; this matches the
    semantics of the sibling orchestrators (transcription / qa / kg).
    ``chunk_sets_written`` is the on-disk artifact count and diverges from
    sources whenever more than one view is requested
    (``chunk_sets_written == sources_processed * len(views)``).
    """

    pipeline_id: str
    run_dir: str
    sources_processed: int = 0
    sources_resumed: int = 0
    chunk_sets_written: int = 0
    skipped: int = 0


def _validate_views(views: list[str]) -> None:
    unknown = [v for v in views if v not in KNOWN_CHUNKER_IDS]
    if unknown:
        raise ValueError(f"Unknown chunker_id(s): {unknown}. Known: {sorted(KNOWN_CHUNKER_IDS)}")


def run_chunk_batch(
    input_dir: Path,
    views: list[str],
    pipeline_id: str | None = None,
) -> ChunkBatchResult:
    """Chunk every ``*.json`` file in ``input_dir`` across the given views.

    Args:
        input_dir: Directory of ``EnrichedRecord`` JSON files.
        views: Chunker view IDs to emit (e.g. ``["cep_4k", "bm25_512t"]``);
            must all be registered in ``KNOWN_CHUNKER_IDS``.
        pipeline_id: Optional run identifier. Auto-generated by
            ``ResultsManager`` (e.g. ``YYYYMMDD_HHMMSS_local``) when ``None``;
            reusing an existing ID attaches the chunk stage to that run.

    Returns:
        A :class:`ChunkBatchResult` with the resolved ``pipeline_id``, the
        absolute ``run_dir`` path, and counts of written / skipped files.

    Raises:
        ValueError: If ``views`` contains any unregistered chunker_id.
    """
    _validate_views(views)

    config = ChunkBatchConfig(input_dir=str(input_dir), views=views)
    results_mgr = ResultsManager(
        ResultsConfig().base_dir,
        PipelineType.CHUNK,
        pipeline_id=pipeline_id,
    )
    results_mgr.create_run(
        config,
        input_source=str(input_dir),
        checkpoint_filename=CHECKPOINT_FILENAME,
    )

    checkpoint = CheckpointManager(results_mgr.run_dir / CHECKPOINT_FILENAME)
    chunkers = {view_id: get_chunker(view_id) for view_id in views}

    json_files = sorted(input_dir.glob("*.json"))
    checkpoint.set_total_files(len(json_files))

    if not json_files:
        logger.info("No EnrichedRecord JSON files found in %s", input_dir)
        results_mgr.update_progress(0, 0, 0)
        results_mgr.complete_run(success=True)
        return ChunkBatchResult(
            pipeline_id=results_mgr._pipeline_id or "",
            run_dir=str(results_mgr.run_dir),
        )

    sources_processed = 0
    sources_resumed = 0
    skipped = 0
    failed = 0
    for json_file in json_files:
        try:
            record = EnrichedRecord.model_validate_json(json_file.read_text())
        except ValidationError as exc:
            logger.debug("Skipping non-EnrichedRecord file %s: %s", json_file, exc)
            skipped += 1
            continue

        # Resume mid-run: skip sources the checkpoint already marks completed
        # (mirrors transcription / qa / kg orchestrators). For chunking this
        # rarely matters at <1 s/file, but the convention preserves consistency
        # and avoids re-writing artifacts on idempotent retries.
        if checkpoint.is_completed(record.file_id):
            sources_resumed += 1
            continue

        text = record.transcription_text
        sha = hashlib.sha256(text.encode("utf-8")).hexdigest()

        try:
            for view_id, chunker in chunkers.items():
                chunks: list[Chunk] = chunker.chunk(text, source_file_id=record.file_id)
                chunk_set = ChunkSet(
                    source_file_id=record.file_id,
                    source_filename=record.name,
                    source_text_sha256=sha,
                    views={view_id: chunks},
                    generated_at=datetime.now(UTC),
                )
                view_dir = results_mgr.outputs_dir / view_id
                view_dir.mkdir(parents=True, exist_ok=True)
                chunk_set.save(view_dir / f"{record.file_id}.json")
        except Exception as exc:
            logger.error("Chunking failed for %s: %s", record.file_id, exc)
            checkpoint.mark_failed(record.file_id, str(exc))
            failed += 1
            continue

        checkpoint.mark_completed(record.file_id)
        sources_processed += 1

    # Progress is reported in source units (mirrors sibling orchestrators).
    # Already-resumed sources count toward "completed" so progress is monotonic
    # across rerun invocations.
    results_mgr.update_progress(sources_processed + sources_resumed, failed, len(json_files))
    results_mgr.complete_run(success=(failed == 0))

    return ChunkBatchResult(
        pipeline_id=results_mgr._pipeline_id or "",
        run_dir=str(results_mgr.run_dir),
        sources_processed=sources_processed,
        sources_resumed=sources_resumed,
        chunk_sets_written=sources_processed * len(views),
        skipped=skipped,
    )
